export enum UserType {
  'FACULTY' = 'FACULTY',
  'STUDENT' = 'STUDENT',
  'ADMIN' = 'ADMIN',
}

export enum memberPosition {
  'CHAIR' = 'CHAIR',
  'VICE_CHAIR' = 'VICE_CHAIR',
  'SECRETARY' = 'SECRETARY',
  'BRANCH_COUNSELLOR' = 'BRANCH_COUNSELLOR',
  'SOCIETY_COUNSELLOR' = 'SOCIETY_COUNSELLOR',
  'SOCIETY_CHAIR' = 'SOCIETY_CHAIR',
  'SOCIETY_VICE_CHAIR' = 'SOCIETY_VICE_CHAIR',
  'SOCIETY_SECRETARY' = 'SOCIETY_SECRETARY',
  'SOCIETY_TREASURER' = 'SOCIETY_TREASURER',
  'TREASURER' = 'TREASURER',
}
